spring:
  shell:
    interactive:
      enabled: true
    history:
      name: ".relayer-cli-history"
logging:
  level:
    root: off
grpc:
  client:
    admin:
      negotiation-type: plaintext
auth:
  username: ${AUTH_USERNAME:admin}
  password: ${AUTH_PASSWORD:admin}