; #########################
;    program template
;
; ########################
; >>>>> should appends to /etc/supervisord.conf
;
[program:l2-relayer]
directory=/l2-relayer
; >>>>> launch command with absolute path, !!!!MODIFY IT!!!!
command=@START_CMD
; >>>>> not start as supervisor service
autostart=true
startsecs=3
; >>>>> supervisor will relaunch this program when it's killed
autorestart=true
startretries=3
user=root
redirect_stderr=true
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=20
stdout_logfile=/tmp/l2_relayer_stdout.log
stopwaitsecs=60