FROM eclipse-temurin:21-jre AS base

ENV TZ=Asia/Shanghai
ENV LANG=en_US.UTF-8
ENV RELAYER_HOME=/l2-relayer

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       tini haveged openssl gettext-base jq supervisor netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /l2-relayer /etc/supervisord.d

ADD l2-relayer.tar.gz /

ENTRYPOINT ["tini", "--", "/l2-relayer/bin/entrypoint.sh"]
